[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
    [".antidote".clone]
        args = ["--depth", "1"]
