[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0001,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0008"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001%"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\""
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001d"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u000c"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u0006"
key = "F"
mods = "Command"

[window]
decorations = "none"
opacity = 0.95

[window.position]
x = 5
